### PR TITLE
Update to rpc-gatts.md

### PR DESCRIPTION
**Pull request by markterrill**
It took me 2 hours to figure it out. Hopefully this will help someone else!
If it's accepted quickly and you think it's a good idea I'll contribute more.

### CODE REVIEW

**Comment by rojer** [comment]
this is exactly what we need, thank you!

**Comment by rojer** [comment]
@cpq, please review

**Comment by cpq** [comment]
https://mongoose-os.com/docs/mongoose-os/api/rpc/rpc-gatts.md#lightning-how-to

Thank you!

**Comment by markterrill** [comment]
Pleasure!
I'll do a few more as I go.

**Pull request merged**
