### PR TITLE
Updating Blynk C API Docs with example and explanations

### PR DESCRIPTION
**Pull request by marcosboger**
I recently used Mongoose OS with Blynk API and C Source code and having no examples in the Docs made it a lot harder to understand how to use the API. I also put an explanation that the API works only with Blynk Legacy, as trying to use it with the new Blynk IoT did not work. I think that these changes can make connecting Mongoose OS with Blynk easier for inexperienced users.

### CODE REVIEW

**Comment by rojer** [comment]
very good, thanks! while at it, can you also fix video embedding? looks like iframe no longer works, if there's no way to embed it, please replace with a link.

**Comment by marcosboger** [comment]
Actually, I was checking and it does work in the web page of the [docs](https://mongoose-os.com/docs/mongoose-os/api/cloud/blynk.md) 

I think it doesn't work only in the **.md** file. I tried playing with the height to make it look a little bigger, but I think the way the web page renders the iframe in the **.md** file is differente because I couldn't do it.

Do you think we should make any more changes or leave it as is?

**Comment by marcosboger** [comment]
Just doing a follow up on the Pull Request

**Comment by rojer** [comment]
sorry, fell though the cracks. merged, thanks!

**Pull request merged**
