### PR TITLE
more url corrections

### PR DESCRIPTION
**Pull request by a2800276**
This introduces some more corrections to urls and a rough tool to check the repo.
I think the bulk of the incorrect links are due to some a glitch in the code generating the api docs (as well as a couple of incorrect links within the individual linked apis ...)
I'll play with that next, but will issue a seperate PR to not make things too confusing.

### CODE REVIEW

**Comment by a2800276** [comment]
I've gone ahead and added the changes I made to genapi.js as well, this corrects most of the errors in the API docs linking to src and include files on github. 

I did not check in the generated files because I'm not sure how you guys have things set up, the Makefile has some dependencies on files outside the repo and I'm not sure how things should be structured (e.g. use `frozen` from with the mongoose-os repo or the stand-alone `frozen`)

**Comment by a2800276** [comment]
This is the report of the remaining url errors that `tools/checkLinks.js` finds, along with comments:

---------
403 : Forbidden
(not sure what's up with these, maybe Mouser doesn't accept HEAD requests, the links all seem to work in the browser)
---------
https://www.mouser.ie/ProductDetail/Espressif-Systems/ESP32-PICO-KIT?qs=%2fha2pyFadug%252b4OsJtZ6BWCK54algBDG2cu7MN2ivj8E%3d
affects: mongoose-os/quickstart/devboards.md

https://www.mouser.ie/ProductDetail/STMicroelectronics/B-L475E-IOT01A2?qs=sGAEpiMZZMtw0nEwywcFgLsaY7JiSlO%2fppdYl3jRSsNnt9SKMZclVw%3d%3d
affects: mongoose-os/quickstart/devboards.md

https://www.mouser.ie/ProductDetail/STMicroelectronics/NUCLEO-F746ZG?qs=sGAEpiMZZMtw0nEwywcFgCOvL%2fCIMT%2f2w01SZnal1Ngwgxcd9gFiJw%3d%3d
affects: mongoose-os/quickstart/devboards.md

https://www.mouser.ie/All-Manufacturers/_/N-0?Keyword=esp32-devkit-c
affects: mongoose-os/quickstart/devboards.md

https://www.mouser.ie/ProductDetail/Texas-Instruments/LAUNCHCC3220MODASF?qs=%2fha2pyFadujqlJX34r9ZGoAmtkXcNzJj%252bZ4VZVBUJdhvqS35TYOi%252bA%3d%3d
affects: mongoose-os/quickstart/devboards.md

https://eu.mouser.com/new/Silicon-Laboratories/silabs-si7005/
affects: mongoose-os/api/drivers/si7005.md


---------
301 : Moved Permanently
(mainly typos in included API repos. I'm ont sure if the Bluetooth Spec links have been removed by the SIG, that would be disadventageous. I'll see if I find time to make PRs to the external repos)
---------
http://www.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf
new: https://www.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf
affects: mongoose-os/api/arduino/arduino-adafruit-bme280.md

http://forum.arduino.cc/index.php?topic=171056.0
new: https://forum.arduino.cc/index.php?topic=171056.0
affects: mongoose-os/api/arduino/arduino-md-parola.md

http://www.microchip.com/wwwproducts/en/ATECC508A
new: https://www.microchip.com/wwwproducts/en/ATECC508A
affects: mongoose-os/api/cloud/azure.md

https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.generic_access.xml
new: /specifications/gatt/removed
affects: mongoose-os/api/rpc/rpc-service-gattc.md

https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.generic_attribute.xml
new: /specifications/gatt/removed
affects: mongoose-os/api/rpc/rpc-service-gattc.md

https://www.ibm.com/internet-of-things/spotlight/watson-iot-platform
new: //www.ibm.com/internet-of-things/solutions/iot-platform/watson-iot-platform
affects: mongoose-os/cloud/watson.md

http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
new: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
affects: mongoose-os/cloud/aws.md


---------
404 : Not Found
(vishay no longer has the device numbers, the other bad links are more remenants of genapi, though I'm not sure what the correct links are supposed to be, e.g. I've not been able to find where `mbuf` is implemented, the header is in `include/common` but there's no corresponding c while in `src/common` )
---------
https://www.vishay.com/docs/84339/designingveml6075.pdf
affects: mongoose-os/api/drivers/veml6075-i2c.md

https://github.com/cesanta/mongoose-os/blob/master/include/mg_str.h
affects: mongoose-os/api/core/mg_str.h.md

https://github.com/cesanta/mongoose-os/blob/master/src/mbuf.c
affects: mongoose-os/api/core/mbuf.h.md

https://github.com/cesanta/mongoose-os/blob/master/include/cs_dbg.h
affects: mongoose-os/api/core/cs_dbg.h.md

https://github.com/cesanta/mongoose-os/blob/master/src/mgos_app.c
affects: mongoose-os/api/core/mgos_app.h.md

https://github.com/cesanta/mongoose-os/blob/master/src/mg_str.c
affects: mongoose-os/api/core/mg_str.h.md

https://github.com/cesanta/mongoose-os/blob/master/include/mbuf.h
affects: mongoose-os/api/core/mbuf.h.md

https://github.com/cesanta/mongoose-os/blob/master/src/cs_dbg.c
affects: mongoose-os/api/core/cs_dbg.h.md

https://github.com/cesanta/mongoose-os/blob/master/src/mgos_iram.c
affects: mongoose-os/api/core/mgos_iram.h.md

**Comment by a2800276** [comment]
... any interest in this?

**Comment by a2800276** [comment]
This PR has been lingering for months now. In case there is something I can do to improve it,  let me know. Else please either merge or delete.

**Comment by rojer** [comment]
seems reasonable to me. @cpq ?

**Pull request merged**
