### PR TITLE
Add API call information

### PR DESCRIPTION
**Pull request by markterrill**
To save someone else a few hours stuffing around

### CODE REVIEW

**Comment by rojer** [comment]
screen out the identifiers and LG

**Comment by markterrill** [comment]
Hey Rojer, it's fake identifiers, but correct string lengths (as that's one of the checks). Even used the American movie style 555 inclusion at the end of each of the identifiers.

**Comment by rojer** [comment]
ok, can you make them _obviously_ fake though, like XXXXX or 12345678 or some such

**Comment by rojer** [comment]
keeping the length correct, of course

**Comment by markterrill** [comment]
Yeah done.

**Pull request merged**
